name: SGDuels
version: 0.0.1
author: AkabeX86
main: com.akabex86.main.Main
api-version: 1.18
depend: [ProtocolLib]
softdepend: [PlaceholderAPI,WorldGuard]

commands:
  world:
    aliases: [mw,mworld]
    permission: sgduels.world
    usage: /world <world>
    description: World Teleport.
